### ISSUE TITLE
blocking error from main branch

### ISSUE THREAD

**Issue by woodyafortunato** [SteveTownsend/WeaponSpeedEffectsFix#2]
Program.cs(124,28): error CS1061: 'T' does not contain a definition for 'ContainedFormLinks' and no accessible extension method 'ContainedFormLinks' accepting a first argument of type 'T' could be found (are you missing a using directive or an assembly reference?)
Program.cs(124,28): error CS1061: 'T' does not contain a definition for 'ContainedFormLinks' and no accessible extension method 'ContainedFormLinks' accepting a first argument of type 'T' could be found (are you missing a using directive or an assembly reference?)

**Comment by SteveTownsend** [comment]
Most likely mismatched dependencies. Use "Match" in the patcher profile and see if that helps.
I'll try to refresh my patchers to use latest Synthesis/Mutagen assemblies in the next couple of months,
